.PHONY:all
all:test1 test2 test3 test4 test5 test6 test7 test8 test9

test1:exp1.c
	gcc -o test1 exp1.c
test2:exp2.c
	gcc -o test2 exp2.c
test3:exp3.c
	gcc -o test3 exp3.c
test4:exp4.c
	gcc -o test4 exp4.c
test5:exp5.c
	gcc -o test5 exp5.c
test6:exp6.c
	gcc -o test6 exp6.c
test7:exp7.c
	gcc -o test7 exp7.c
test8:exp8.c
	gcc -o test8 exp8.c
test9:exp9.c
	gcc -o test9 exp9.c

.PHONY:clean
clean:
	rm -f test*